language: go
go:
  - '1.3'
  - '1.4'
  - '1.5'

sudo: required
services:
  - docker

deploy:
  - provider: script
    script: scripts/publish $TRAVIS_COMMIT
    on:
      branch: master
      go: '1.5'
  - provider: script
    script: scripts/publish $TRAVIS_TAG
    on:
      tags: true
      go: '1.5'
